Add recommender test request generation script (#174)
Two issues observed so far:
1. Some clicked articles are missing in the exported data (just contain
the data from the day of 3/25), like the following error shows; so need
to add exception check in the `poprox.py` code.
```
Traceback (most recent call last):
  File "/workspaces/poprox-recommender/tests/generate_test_request.py", line 60, in <module>
    get_single_request()
  File "/workspaces/poprox-recommender/tests/generate_test_request.py", line 26, in get_single_request
    requests = list(eval_data.iter_profiles())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/poprox-recommender/src/poprox_recommender/data/poprox.py", line 88, in iter_profiles
    article = self.lookup_clicked_article(article_row.article_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/poprox-recommender/src/poprox_recommender/data/poprox.py", line 136, in lookup_clicked_article
    article_row = self.clicked_articles_df.loc[str(article_id)]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/vscode/poprox-venv/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/poprox-venv/lib/python3.12/site-packages/pandas/core/indexing.py", line 1431, in _getitem_axis
    return self._get_label(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/poprox-venv/lib/python3.12/site-packages/pandas/core/indexing.py", line 1381, in _get_label
    return self.obj.xs(label, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/poprox-venv/lib/python3.12/site-packages/pandas/core/generic.py", line 4301, in xs
    loc = index.get_loc(key)
          ^^^^^^^^^^^^^^^^^^
  File "/home/vscode/poprox-venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: '35506a36-3346-487c-82b4-8821b0850057'
```
2. If we want to test with our own account, there's no way to
differentiate who is who since all `account_id` in the export data now
is random. We might be able to tell if we additionally send test emails
during the same day (so experimenter's ids would get two newsletters,
instead of one), but It's not a sustainable way.